### ISSUE TITLE
[Forge] Minecraft no longer starts in 4.2.2

### ISSUE THREAD

**Issue by Mickeon** [MayaqqDev/Estrogen#81] opened 2024-04-09 17:28 UTC
The game crashes on start-up. Removing **Create: Estrogen**, or downgrading to 4.2.1 allows the game to load just fine.

Attached is the crash log:
[crash-2024-04-09_19.23.52-client.txt](https://github.com/MayaqqDev/Estrogen/files/14922003/crash-2024-04-09_19.23.52-client.txt)

**Comment by jadeiseepy** [comment] 2024-04-09 17:39
Can reproduce with NeoForge 47.1.104 and Forge 47.2.23 with just Estrogen + Create installed.

**Comment by jadeiseepy** [comment] 2024-04-09 17:58
looks like [`3d114fc`](https://github.com/MayaqqDev/Estrogen/commit/3d114fce6aa2be64d2cf7d43903319e93489aaae) is to blame

**Comment by jadeiseepy** [comment] 2024-04-09 18:06
[this build](https://github.com/MayaqqDev/Estrogen/files/14922445/Estrogen-4.2.2%2B1.20.1-forge.zip) should work for now, but you can't shoot estrogen pills out of potato cannons

**Comment by MayaqqDev** [comment] 2024-04-10 14:29
Fixed in new release

**Closed as completed by MayaqqDev** 2024-04-10 14:29 UTC
